apiVersion: apps/v1
kind: Deployment
metadata:
  name: memorder-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: memorder-frontend
  template:
    metadata:
      labels:
        app: memorder-frontend
    spec:
      containers:
        - name: frontend
          image: memorder-frontend:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 3000
