apiVersion: v1
kind: Service
metadata:
  name: memorder-frontend-service
spec:
  selector:
    app: memorder-frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: NodePort
